name: Generate RULE-SET for Premium Edition of Clash
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RULESET_LIST: |
        (
          "netflix"
          "youtube"
          "primevideo"
          "hbo"
          "disney"
          "roku"
          "spotify"
          "tiktok"
          "twitch"
          "xvideos"
          "pornhub"
          "dmm"
          "dlsite"
          "telegram"
          "speedtest"
          "openai"
          "playstation"
          "nintendo"
          "xbox"
          "steam"
          "ea"
          "epicgames"
          "ubisoft"
        )

    steps:
      - name: Compare latest tags and set variables
        run: |
          upstreamLatestTag=$(curl -sSL --connect-timeout 5 --retry 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/daiyeqi/domain-list-custom/releases/latest | grep "tag_name" | cut -d\" -f4)
          thisLatestTag=$(curl -sSL --connect-timeout 5 --retry 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ $upstreamLatestTag != $thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV
        shell: bash

      - name: Generate Clash RULE-SET file
        if: ${{ env.NeedToSync }}
        run: |
          array=${{ env.RULESET_LIST }}
          for item in "${array[@]}"
          do
            echo "payload:" > ${item}.txt
            curl -sSL https://raw.githubusercontent.com/daiyeqi/domain-list-custom/release/${item}.txt | grep -E "^(full|domain):" | awk -F ':' '{printf "  - |+.%s|\n", $2}' | sed "s/|/'/g" >> ${item}.txt
          done

      - name: Move files to publish directory
        if: ${{ env.NeedToSync }}
        run: |
          mkdir -p publish
          cp *.txt ./publish/

      - name: Release and upload assets
        if: ${{ env.NeedToSync }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        if: ${{ env.NeedToSync }}
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
